baseURL: http://localhost:1313
languageCode: en-us
defaultContentLanguage: en
title: Vibe
log: true
verbose: true
enableRobotsTXT: true
enableGitInfo: true
disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS
buildDrafts: true
buildExpired: true
buildFuture: true
minify:
  disableSVG: true
