defaultDescription: Vibe packs digital whiteboard technology, video conferencing, wireless screencasting, third-party app integrations, and more into a sleek package.
appURL: https://app.vibe.us/
apiURL: https://api.vibe.us/v1/
allowIndex: true
gtmId: GTM-5GF6X7Z
